import type {
  ItineraryItem,
  PackGroup,
  Place,
  Reservation,
  Traveler,
} from "./types";

export const travelers: Traveler[] = [
  {
    id: "jazmin",
    name: "Jazmín Torres",
    role: "15 años",
    facts: [
      { label: "DNI", value: "51358397" },
      { label: "Nacimiento", value: "18 ago 2011" },
      { label: "Pasaporte", value: "AAL598908" },
      { label: "Emisión", value: "5 jun 2025" },
      { label: "Vencimiento", value: "5 jun 2030" },
      { label: "DS-160", value: "AA00FDILYD" },
      { label: "Assist Card", value: "540 25434495 05C PR043 / 1" },
      { label: "Billete vuelta", value: "044-7504385048" },
    ],
  },
  {
    id: "geronimo",
    name: "Gerónimo Torres",
    role: "9 años",
    facts: [
      { label: "DNI", value: "56296900" },
      { label: "Nacimiento", value: "12 abr 2017" },
      { label: "Pasaporte", value: "AAL606257" },
      { label: "Emisión", value: "5 jun 2025" },
      { label: "Vencimiento", value: "5 jun 2030" },
      { label: "DS-160", value: "AA00FDINQ3" },
      { label: "Assist Card", value: "540 25434496 05C PR043 / 1" },
      { label: "Billete vuelta", value: "044-7504385050" },
    ],
  },
  {
    id: "yamila",
    name: "Yamila Pomi",
    role: "Adulta",
    facts: [
      { label: "DNI", value: "33069618" },
      { label: "Nacimiento", value: "11 may 1987" },
      { label: "Pasaporte", value: "AAJ894600" },
      { label: "Billete vuelta", value: "044-7504385049" },
    ],
  },
];

export const documents: PackGroup = {
  id: "documentos",
  title: "Documentación",
  items: [
    { id: "pasaporte", label: "Pasaporte / DNI", done: true },
    { id: "visa", label: "Visa", done: true },
    { id: "seguro", label: "Seguro de viaje", done: true },
    { id: "hotel", label: "Reservas de hotel", done: true },
    { id: "tickets", label: "Tickets de vuelo", done: true },
    { id: "permiso", label: "Permiso de viaje", done: false },
    { id: "partidas", label: "Partidas de nacimiento", done: false },
    { id: "usb", label: "USB", done: false },
    { id: "usbc", label: "USB C", done: false },
    { id: "power-doc", label: "Power bank", done: false },
  ],
};

export const packing: PackGroup[] = [
  {
    id: "ropa",
    title: "Ropa",
    items: [
      { id: "zapatillas", label: "Zapatillas", done: true },
      { id: "camisetas", label: "Camisetas", done: true },
      { id: "jeans", label: "Jeans", done: true },
      { id: "camperas", label: "Camperas", done: true },
    ],
  },
  {
    id: "higiene",
    title: "Higiene",
    items: [
      { id: "cepillo", label: "Cepillo de dientes", done: true },
      { id: "pasta", label: "Pasta dental", done: false },
      { id: "desodorante", label: "Desodorante", done: true },
      { id: "protector", label: "Protector solar", done: true },
      { id: "jabon", label: "Jabón", done: true },
      { id: "shampoo", label: "Shampoo", done: false },
      { id: "acondicionador", label: "Acondicionador", done: false },
      { id: "toallitas", label: "Toallitas íntimas", done: false },
    ],
  },
  {
    id: "dispositivos",
    title: "Dispositivos",
    items: [
      { id: "cargador", label: "Cargador", done: true },
      { id: "powerbank", label: "Power bank", done: true },
      { id: "ebook", label: "Libro electrónico", done: true },
    ],
  },
  {
    id: "botiquin",
    title: "Botiquín",
    items: [
      { id: "ibuprofeno", label: "Ibuprofeno", done: false },
      { id: "paracetamol", label: "Paracetamol", done: false },
      { id: "buscapina", label: "Buscapina", done: false },
      { id: "reliveran", label: "Reliverán", done: false },
    ],
  },
];

export const places: Place[] = [
  {
    id: "hollywood",
    category: "Parques",
    name: "Disney's Hollywood Studios",
    area: "Walt Disney World",
    address: "Disney's Hollywood Studios, Cypress Dr, Orlando, FL 32830",
    blurb: "Star Wars, Tower of Terror y la montaña de los Muppets. Entrada el 30 de septiembre.",
    hours: "Desde la apertura, el 30 sep",
    highlights: [
      {
        title: "Rise of the Resistance",
        detail: "Hacerla primero. Si la fila supera 90 minutos, dejarla para las 19:30.",
        priority: "imperdible",
      },
      {
        title: "Millennium Falcon: Smugglers Run",
        detail: "Pedir ser los pilotos.",
        priority: "si",
      },
      {
        title: "The Twilight Zone Tower of Terror",
        detail: "Caída libre.",
        priority: "si",
      },
      {
        title: "Rock ’n’ Roller Coaster",
        detail: "Temática nueva de Los Muppets. Imperdible para Jazmín.",
        priority: "imperdible",
      },
      {
        title: "Toy Story Mania!",
        detail: "Apenas abran, entrar por Toy Story Land.",
        priority: "si",
      },
      {
        title: "Indiana Jones o La Sirenita",
        detail: "A las 17:30. Bajo techo o con sombra, para descansar las piernas.",
        priority: "opcional",
      },
      {
        title: "Fantasmic!",
        detail: "Show de cierre a las 20:00. Estar en el teatro 45 minutos antes.",
        priority: "imperdible",
      },
    ],
    tips: [
      "El orden del día: Toy Story Land, Galaxy’s Edge, Sunset Boulevard y Fantasmic! al final.",
      "Star Wars: Galaxy’s Edge de noche cambia el clima del lugar.",
    ],
  },
  {
    id: "magic-kingdom",
    category: "Parques",
    name: "Magic Kingdom",
    area: "Walt Disney World",
    address: "Magic Kingdom Park, 4720 Caribbean Way, Orlando, FL 32830",
    blurb: "Mickey’s Not-So-Scary Halloween Party. La entrada es a las 16:00 del 1 de octubre.",
    hours: "Fiesta desde las 16:00",
    highlights: [
      {
        title: "Seven Dwarfs Mine Train",
        detail: "En la pre-fiesta, de 16:00 a 18:30. No cambia durante la fiesta.",
        priority: "si",
      },
      {
        title: "Tiana’s Bayou Adventure",
        detail: "La otra opción de la pre-fiesta.",
        priority: "si",
      },
      {
        title: "Haunted Mansion",
        detail: "A las 19:00, con el ambiente de Halloween.",
        priority: "imperdible",
      },
      {
        title: "Space Mountain",
        detail: "A oscuras y con música de Halloween.",
        priority: "imperdible",
      },
      {
        title: "TRON Lightcycle / Run",
        detail: "Mejor de noche.",
        priority: "si",
      },
      {
        title: "Fuegos Spooktacular",
        detail: "21:15, frente al castillo.",
        priority: "imperdible",
      },
      {
        title: "Mickey’s Boo-to-You",
        detail: "Segundo desfile a las 23:15. El primero se llena; el segundo deja primera fila.",
        priority: "imperdible",
      },
      {
        title: "Carousel of Progress",
        detail: "Para sentarse y descansar.",
        priority: "paso",
      },
    ],
    tips: [
      "Adventureland: Jungle Cruise, Pirates of the Caribbean, Magic Carpets, Swiss Family Treehouse, Tiki Room.",
      "Frontierland: Big Thunder Mountain y Tiana’s Bayou Adventure.",
      "Fantasyland: Mine Train, Mad Tea Party y The Barnstormer.",
      "Tomorrowland: TRON, Space Mountain, Carousel of Progress y Astro Orbiter.",
    ],
  },
  {
    id: "universal",
    category: "Parques",
    name: "Universal Studios Florida",
    area: "Universal Orlando",
    address: "Universal Studios Florida, 6000 Universal Blvd, Orlando, FL 32819",
    blurb: "Diagon Alley, la momia y Minions. Día de parque el 5 de octubre.",
    hours: "Apertura, 5 oct",
    highlights: [
      {
        title: "Harry Potter and the Escape from Gringotts",
        detail: "Apenas abran, ir al fondo, a Diagon Alley.",
        priority: "imperdible",
      },
      {
        title: "Revenge of the Mummy",
        detail: "Montaña rusa bajo techo, al salir de Harry Potter.",
        priority: "si",
      },
      {
        title: "Transformers: The Ride-3D",
        detail: "Simulador con efectos.",
        priority: "si",
      },
      {
        title: "Despicable Me Minion Mayhem",
        detail: "Simulador. Vale la pena.",
        priority: "si",
      },
      {
        title: "The Simpsons Ride",
        detail: "Simulador en Springfield.",
        priority: "si",
      },
      {
        title: "Fast & Furious – Supercharged",
        detail: "Proyección.",
        priority: "si",
      },
      {
        title: "Men in Black Alien Attack",
        detail: "Se puede hacer, sin priorizarla.",
        priority: "paso",
      },
      {
        title: "Villain-Con Minion Blast",
        detail: "La de disparar. La dejamos.",
        priority: "paso",
      },
    ],
    tips: [
      "De noche, el dragón de Diagon Alley escupe fuego y los callejones se ven distintos.",
      "Race Through New York con Jimmy Fallon queda como alternativa si sobra tiempo.",
    ],
  },
  {
    id: "islands",
    category: "Parques",
    name: "Islands of Adventure",
    area: "Universal Orlando",
    address: "Universal's Islands of Adventure, 6000 Universal Blvd, Orlando, FL 32819",
    blurb: "Hagrid, VelociCoaster, Marvel y el agua. Día de parque el 6 de octubre.",
    hours: "Apertura, 6 oct",
    highlights: [
      {
        title: "Hagrid’s Magical Creatures Motorbike Adventure",
        detail: "Ir directo apenas abran.",
        priority: "imperdible",
      },
      {
        title: "Jurassic World VelociCoaster",
        detail: "Al lado de Hagrid. Montaña extrema.",
        priority: "imperdible",
      },
      {
        title: "The Incredible Hulk Coaster",
        detail: "Marvel Super Hero Island.",
        priority: "si",
      },
      {
        title: "The Amazing Adventures of Spider-Man",
        detail: "Atracción 3D con efectos.",
        priority: "si",
      },
      {
        title: "Harry Potter and the Forbidden Journey",
        detail: "En Hogsmeade.",
        priority: "si",
      },
      {
        title: "Jurassic Park River Adventure",
        detail: "Opcional: se mojan.",
        priority: "opcional",
      },
      {
        title: "Popeye & Bluto’s Bilge-Rat Barges",
        detail: "Rápidos. Se pueden guardar las zapatillas.",
        priority: "opcional",
      },
      {
        title: "Dudley Do-Right’s Ripsaw Falls",
        detail: "Moja mucho.",
        priority: "opcional",
      },
      {
        title: "King Kong",
        detail: "Skull Island.",
        priority: "opcional",
      },
      {
        title: "Doctor Doom’s Fearfall",
        detail: "Torre de caída.",
        priority: "opcional",
      },
      {
        title: "Tren de Seuss Landing",
        detail: "Recorre el área desde arriba. Bueno para bajar el ritmo.",
        priority: "paso",
      },
    ],
    tips: [
      "El orden: Hagrid, VelociCoaster, después Marvel. El agua, solo si quieren mojarse.",
    ],
  },
  {
    id: "kennedy",
    category: "Parques",
    name: "Kennedy Space Center",
    area: "Merritt Island",
    address: "Kennedy Space Center Visitor Complex, Space Commerce Way, Merritt Island, FL 32953",
    blurb: "Día fuera de Orlando, el 3 de octubre. El transbordador Atlantis es la parada que no se salta.",
    hours: "09:00 – 15:00",
    highlights: [
      {
        title: "Space Shuttle Atlantis",
        detail: "La exhibición principal. Calcular unas 6 horas en todo el complejo.",
        priority: "imperdible",
      },
    ],
    tips: [
      "Sale antes de la playa. A las 15:30 siguen hacia Cocoa Beach.",
      "Pedir un mapa al entrar.",
    ],
  },
  {
    id: "outlets",
    category: "Compras",
    name: "Orlando International Premium Outlets",
    area: "International Drive",
    address: "4951 International Dr, Orlando, FL 32819",
    blurb: "Mañana del 1 de octubre, antes de la fiesta de Mickey.",
    hours: "09:30 – 13:30",
    highlights: [
      { title: "Character Warehouse", detail: "Outlet de Disney. Ir directo.", priority: "imperdible" },
      { title: "Adidas", priority: "si" },
      { title: "Victoria’s Secret", priority: "si" },
    ],
    tips: ["Cuatro horas alcanzan si entran primero a Disney y Adidas."],
  },
  {
    id: "vineland",
    category: "Compras",
    name: "Vineland Premium Outlets",
    area: "Lake Buena Vista",
    address: "8200 Vineland Ave, Orlando, FL 32821",
    blurb: "Otro Character Warehouse, por si en International Drive no consiguen talle.",
    highlights: [
      { title: "Character Warehouse", detail: "Outlet de Disney.", priority: "si" },
    ],
    tips: ["No está en un día fijo del itinerario. Sirve como alternativa de compras."],
  },
  {
    id: "marketplace",
    category: "Compras",
    name: "Orlando Outlet Marketplace",
    area: "Orlando",
    address: "Orlando Outlet Marketplace, Orlando, FL",
    blurb: "Parada corta si falta algo de Adidas.",
    highlights: [{ title: "Adidas", priority: "opcional" }],
    tips: ["Queda como reserva de la lista de outlets, sin horario asignado."],
  },
  {
    id: "florida-mall",
    category: "Compras",
    name: "Florida Mall",
    area: "Orange Blossom Trail",
    address: "8001 S Orange Blossom Trl, Orlando, FL 32809",
    blurb: "Compras bajo techo el 2 de octubre, el día después de la fiesta.",
    hours: "11:00 – 15:00",
    highlights: [
      {
        title: "Primark",
        detail: "El segundo piso es de Disney y es de lo más barato en ropa temática.",
        priority: "imperdible",
      },
    ],
    tips: ["Calcular 4 horas. Después, Crumbl Cookies."],
  },
  {
    id: "crumbl",
    category: "Compras",
    name: "Crumbl Cookies",
    area: "Cerca de Florida Mall",
    address: "11551 Regency Village Dr, Orlando, FL 32821",
    blurb: "Galletas gigantes para la merienda del 2 de octubre.",
    hours: "15:30",
    highlights: [
      { title: "Galletas de la semana", detail: "Pasan 30 minutos. No hace falta más.", priority: "si" },
    ],
    tips: ["Queda después de Florida Mall, camino de vuelta."],
  },
  {
    id: "walmart",
    category: "Compras",
    name: "Walmart Supercenter",
    area: "Sand Lake",
    address: "8101 S John Young Pkwy, Orlando, FL 32819",
    blurb: "Primera compra del viaje: agua, snacks y desayuno para los días de parque.",
    hours: "15:30 – 17:30 el 29 sep",
    highlights: [
      {
        title: "Provisiones",
        detail: "Agua, snacks y desayunos. Este local tiene buena sección de souvenirs baratos.",
        priority: "imperdible",
      },
    ],
    tips: ["Ir apenas tengan el auto, antes de instalarse del todo."],
  },
  {
    id: "cocoa",
    category: "Playas",
    name: "Cocoa Beach",
    area: "Costa atlántica",
    address: "150 E Columbia Ln, Cocoa Beach, FL 32931",
    blurb: "La mejor zona para surfear en familia: olas constantes y fondo de arena.",
    hours: "15:30 – 18:30 el 3 oct",
    highlights: [
      {
        title: "Ron Jon Surf School",
        detail: "La escuela más conocida para chicos. Clase de unas 3 horas.",
        priority: "imperdible",
      },
    ],
    tips: [
      "Va después de Kennedy Space Center.",
      "En la agenda también figura una visita suelta el 5 de noviembre, de 09:00 a 17:00, todavía pendiente.",
    ],
    link: {
      label: "Clases de surf",
      href: "https://ronjonsurfschool.com/surf-lessons",
    },
  },
  {
    id: "disney-springs",
    category: "Paseos",
    name: "Disney Springs",
    area: "Lake Buena Vista",
    address: "1508 E Buena Vista Dr, Lake Buena Vista, FL 32830",
    blurb: "Paseo de la primera noche, sin entrada de parque.",
    hours: "18:30 – 21:30 el 29 sep",
    highlights: [
      {
        title: "Tienda Coca-Cola",
        detail: "Subir a la terraza para la degustación de gaseosas del mundo.",
        priority: "imperdible",
      },
    ],
    tips: ["Tres horas alcanzan. Es un paseo, no un parque."],
  },
  {
    id: "mcdonalds",
    category: "Paseos",
    name: "McDonald’s de Sand Lake",
    area: "International Drive",
    address: "6875 Sand Lake Rd, Orlando, FL 32819",
    blurb: "El McDonald’s más grande del mundo. Almuerzo del 1 de octubre, entre los outlets y el hotel.",
    hours: "13:30 – 14:30",
    highlights: [
      {
        title: "Almuerzo rápido",
        detail: "Una hora, y después al hotel a cambiarse para la fiesta.",
        priority: "si",
      },
    ],
    tips: ["No alargar: Magic Kingdom entra a las 16:00."],
  },
  {
    id: "hotel",
    category: "Alojamiento",
    name: "Baymont by Wyndham",
    area: "Downtown Orlando",
    address: "2500 33rd St, Orlando, FL 32839",
    blurb: "Developer Inn Downtown Orlando. Check-in el 29 de septiembre a las 16:00.",
    hours: "Estadía 29 sep – 13 oct",
    phone: "+14078016365",
    highlights: [
      { title: "Teléfono", detail: "+1 407 801 6365", priority: "si" },
    ],
    tips: [
      "El 1 de octubre vuelven a cambiarse entre el almuerzo y Magic Kingdom.",
      "El vuelo de vuelta sale de Miami el 10 de octubre.",
    ],
  },
];

export const reservations: Reservation[] = [
  {
    id: "vuelo-ida",
    category: "vuelo",
    title: "Vuelo de ida",
    provider: "Avianca · Smiles",
    status: "pagado",
    costUsd: 977,
    start: "2026-09-29",
    summary: "EZE 01:35 → Bogotá → MCO 14:50. AV218 y AV216.",
    codes: [
      { label: "Localizador Smiles", value: "ARGTXY" },
      { label: "Localizador Avianca", value: "ARGTXYEZE" },
    ],
    facts: [
      { label: "Tramo 1", value: "AV218 · EZE 29 sep 01:35" },
      { label: "Escala", value: "Bogotá 06:10 – 09:30" },
      { label: "Tramo 2", value: "AV216 · MCO 29 sep 14:50" },
      { label: "Salida", value: "Aeropuerto de Ezeiza" },
      { label: "Tarifa Smiles", value: "AR$ 36.000" },
      { label: "Millas", value: "336.600 × AR$ 2,68 = AR$ 902.088" },
      { label: "Impuestos", value: "AR$ 528.493,20" },
      { label: "Total en pesos", value: "AR$ 1.466.581,20" },
    ],
    notes: ["La llegada a Orlando es a las 14:50, hora local."],
    checklist: [
      { id: "ida-pasaportes", label: "Pasaportes", done: true },
      { id: "ida-partidas", label: "Partidas de nacimiento", done: true },
      { id: "ida-permiso", label: "Permiso de viaje", done: false },
      { id: "ida-asistencia", label: "Asistencia al viajero", done: false },
      { id: "ida-dni", label: "DNI", done: false },
      { id: "ida-almohada", label: "Almohada de viaje", done: false },
    ],
  },
  {
    id: "vuelo-vuelta",
    category: "vuelo",
    title: "Vuelo de vuelta",
    provider: "Aerolíneas Argentinas · Trip.com",
    status: "pagado",
    costUsd: 896.8,
    start: "2026-10-10",
    summary: "AR1305 desde Miami. Sale 09:10 y llega 19:15.",
    codes: [
      { label: "Reserva Trip.com", value: "1453604326740051" },
      { label: "PIN Trip.com", value: "6341" },
      { label: "Localizador", value: "LFTPGY" },
    ],
    facts: [
      { label: "Vuelo", value: "AR1305" },
      { label: "Sale", value: "Miami (MIA) 10 oct 09:10" },
      { label: "Llega", value: "19:15" },
      { label: "Yamila", value: "Billete 044-7504385049" },
      { label: "Jazmín", value: "Billete 044-7504385048" },
      { label: "Gerónimo", value: "Billete 044-7504385050" },
      { label: "Ítem personal", value: "1 pieza, 3 kg, 40×30×15 cm, bajo el asiento" },
      { label: "Carry-on", value: "1 pieza, 10 kg, 55×35×25 cm" },
      { label: "Bodega", value: "Sin franquicia incluida" },
    ],
    notes: [
      "Sale de Miami, no de Orlando.",
      "No hay valija de bodega incluida.",
    ],
    checklist: [
      { id: "vue-pasaportes", label: "Pasaportes", done: true },
      { id: "vue-partidas", label: "Partidas de nacimiento", done: true },
      { id: "vue-permiso", label: "Permiso de viaje", done: false },
      { id: "vue-dni", label: "DNI", done: false },
      { id: "vue-almohada", label: "Almohada de viaje", done: false },
    ],
  },
  {
    id: "hotel",
    category: "hotel",
    title: "Baymont by Wyndham",
    provider: "Developer Inn Downtown Orlando",
    status: "pagado",
    start: "2026-09-29",
    end: "2026-10-13",
    summary: "Check-in 29 sep a las 16:00. Estadía hasta el 13 oct.",
    codes: [
      { label: "Reserva", value: "91876EE069517" },
      { label: "Solicitud", value: "SU-000199" },
    ],
    facts: [
      { label: "Dirección", value: "2500 33rd St, Orlando, FL 32839" },
      { label: "Teléfono", value: "+1 407 801 6365" },
      { label: "Check-in", value: "29 sep 2026 · 16:00" },
      { label: "Estadía", value: "29 sep – 13 oct 2026" },
    ],
    placeId: "hotel",
  },
  {
    id: "hollywood",
    category: "entrada",
    title: "Hollywood Studios",
    provider: "Walt Disney World",
    status: "pagado",
    costUsd: 566.59,
    start: "2026-09-30",
    summary: "Entrada del 30 de septiembre, desde la apertura.",
    codes: [],
    facts: [
      { label: "Día", value: "30 sep · 09:00" },
      { label: "Parque", value: "Disney's Hollywood Studios" },
    ],
    placeId: "hollywood",
  },
  {
    id: "magic",
    category: "entrada",
    title: "Magic Kingdom Halloween",
    provider: "Mickey’s Not-So-Scary Halloween Party",
    status: "pagado",
    costUsd: 593.22,
    start: "2026-10-01",
    summary: "Fiesta del 1 de octubre desde las 16:00.",
    codes: [],
    facts: [
      { label: "Día", value: "1 oct · 16:00" },
      { label: "Parque", value: "Magic Kingdom" },
    ],
    placeId: "magic-kingdom",
  },
  {
    id: "universal",
    category: "entrada",
    title: "Universal Studios",
    provider: "Universal Orlando",
    status: "pagado",
    costUsd: 508.51,
    start: "2026-10-05",
    summary: "Entrada del 5 de octubre, desde la apertura.",
    codes: [],
    facts: [
      { label: "Día", value: "5 oct · 09:00" },
      { label: "Parque", value: "Universal Studios Florida" },
    ],
    placeId: "universal",
  },
  {
    id: "islands",
    category: "entrada",
    title: "Islands of Adventure",
    provider: "Universal Orlando",
    status: "pagado",
    costUsd: 508.51,
    start: "2026-10-06",
    summary: "Entrada del 6 de octubre, desde la apertura.",
    codes: [],
    facts: [
      { label: "Día", value: "6 oct · 09:00" },
      { label: "Parque", value: "Islands of Adventure" },
    ],
    placeId: "islands",
  },
  {
    id: "seguro",
    category: "seguro",
    title: "Assist Card",
    provider: "AC 150",
    status: "pagado",
    costUsd: 199.68,
    start: "2026-09-29",
    end: "2026-10-10",
    summary: "Cobertura hasta USD 150.000 para Jazmín y Gerónimo.",
    codes: [
      { label: "Jazmín", value: "540 25434495 05C PR043 / 1" },
      { label: "Gerónimo", value: "540 25434496 05C PR043 / 1" },
    ],
    facts: [
      { label: "Producto", value: "AC 150" },
      { label: "Vigencia", value: "29 sep – 10 oct 2026, inclusive" },
      { label: "Cobertura", value: "Hasta USD 150.000" },
      { label: "Jazmín", value: "Documento 51358397" },
      { label: "Gerónimo", value: "Documento 56296900" },
    ],
    notes: ["Yamila no figura en estos vouchers."],
  },
  {
    id: "surf",
    category: "actividad",
    title: "Surf en Cocoa Beach",
    provider: "Ron Jon Surf School",
    status: "pendiente",
    start: "2026-11-05",
    summary: "Visita pendiente, de 09:00 a 17:00. Pedir un mapa.",
    codes: [],
    facts: [
      { label: "Fecha en la agenda", value: "5 nov 2026" },
      { label: "Horario", value: "09:00 – 17:00" },
      { label: "Lugar", value: "Cocoa Beach" },
    ],
    notes: [
      "El 3 de octubre ya hay clase de surf después de Kennedy, de 15:30 a 18:30.",
    ],
    placeId: "cocoa",
  },
];

export const itinerary: ItineraryItem[] = [
  {
    id: "vuelo-ida",
    date: "2026-09-29",
    time: "01:35",
    endTime: "14:50",
    instant: "2026-09-29T01:35:00-03:00",
    clock: "Buenos Aires",
    title: "Vuelo a Orlando",
    summary: "AV218 y AV216. Ezeiza, escala en Bogotá, llegada a MCO 14:50.",
    reservationId: "vuelo-ida",
    plan: [
      "01:35 EZE · AV218",
      "06:10 – 09:30 escala en Bogotá",
      "AV216 hasta Orlando",
      "14:50 llegada a MCO",
    ],
  },
  {
    id: "walmart",
    date: "2026-09-29",
    time: "15:30",
    endTime: "17:30",
    instant: "2026-09-29T15:30:00-04:00",
    clock: "Orlando",
    title: "Compras en Walmart",
    summary: "Agua, snacks y desayunos para los días de parque.",
    placeId: "walmart",
    plan: ["Ir apenas tengan el auto.", "El de Sand Lake tiene souvenirs baratos."],
  },
  {
    id: "checkin",
    date: "2026-09-29",
    time: "16:00",
    instant: "2026-09-29T16:00:00-04:00",
    clock: "Orlando",
    title: "Check-in en el hotel",
    summary: "Baymont by Wyndham, Downtown Orlando.",
    placeId: "hotel",
    reservationId: "hotel",
  },
  {
    id: "springs",
    date: "2026-09-29",
    time: "18:30",
    endTime: "21:30",
    instant: "2026-09-29T18:30:00-04:00",
    clock: "Orlando",
    title: "Disney Springs",
    summary: "Paseo nocturno y terraza de la tienda Coca-Cola.",
    placeId: "disney-springs",
    plan: ["Degustación de gaseosas del mundo en la terraza."],
  },
  {
    id: "hollywood",
    date: "2026-09-30",
    time: "09:00",
    instant: "2026-09-30T09:00:00-04:00",
    clock: "Orlando",
    title: "Hollywood Studios",
    summary: "Rise of the Resistance primero. Fantasmic! a las 20:00.",
    placeId: "hollywood",
    reservationId: "hollywood",
    plan: [
      "Apertura: Toy Story Land y Toy Story Mania!",
      "Galaxy’s Edge: Millennium Falcon como pilotos.",
      "Rise of the Resistance. Si hay más de 90 minutos, volver a las 19:30.",
      "Sunset Boulevard: Tower of Terror y Rock ’n’ Roller de los Muppets.",
      "17:30 Indiana Jones o La Sirenita, para descansar.",
      "20:00 Fantasmic! Llegar 45 minutos antes.",
    ],
  },
  {
    id: "outlets",
    date: "2026-10-01",
    time: "09:30",
    endTime: "13:30",
    instant: "2026-10-01T09:30:00-04:00",
    clock: "Orlando",
    title: "Premium Outlets",
    summary: "Character Warehouse, Adidas y Victoria’s Secret.",
    placeId: "outlets",
    plan: ["Cuatro horas. Entrar primero al outlet de Disney."],
  },
  {
    id: "mcdonalds",
    date: "2026-10-01",
    time: "13:30",
    endTime: "14:30",
    instant: "2026-10-01T13:30:00-04:00",
    clock: "Orlando",
    title: "Almuerzo en McDonald’s",
    summary: "El más grande del mundo, en Sand Lake. Después, al hotel a cambiarse.",
    placeId: "mcdonalds",
  },
  {
    id: "magic",
    date: "2026-10-01",
    time: "16:00",
    endTime: "23:15",
    instant: "2026-10-01T16:00:00-04:00",
    clock: "Orlando",
    title: "Magic Kingdom",
    summary: "Halloween party. Fuegos a las 21:15 y desfile a las 23:15.",
    placeId: "magic-kingdom",
    reservationId: "magic",
    plan: [
      "16:00 – 18:30 pre-fiesta: Seven Dwarfs Mine Train o Tiana’s Bayou Adventure.",
      "19:00 Haunted Mansion.",
      "Space Mountain con la música de Halloween.",
      "21:15 fuegos Spooktacular frente al castillo.",
      "23:15 segundo desfile Boo-to-You, más fácil para primera fila.",
    ],
  },
  {
    id: "florida-mall",
    date: "2026-10-02",
    time: "11:00",
    endTime: "15:00",
    instant: "2026-10-02T11:00:00-04:00",
    clock: "Orlando",
    title: "Florida Mall",
    summary: "Día bajo techo. Directo a Primark, segundo piso Disney.",
    placeId: "florida-mall",
  },
  {
    id: "crumbl",
    date: "2026-10-02",
    time: "15:30",
    instant: "2026-10-02T15:30:00-04:00",
    clock: "Orlando",
    title: "Crumbl Cookies",
    summary: "Galletas para la merienda. Media hora.",
    placeId: "crumbl",
  },
  {
    id: "kennedy",
    date: "2026-10-03",
    time: "09:00",
    endTime: "15:00",
    instant: "2026-10-03T09:00:00-04:00",
    clock: "Orlando",
    title: "Kennedy Space Center",
    summary: "Día fuera de Orlando. Ver el transbordador Atlantis.",
    placeId: "kennedy",
  },
  {
    id: "surf-dia",
    date: "2026-10-03",
    time: "15:30",
    endTime: "18:30",
    instant: "2026-10-03T15:30:00-04:00",
    clock: "Orlando",
    title: "Surf en Cocoa Beach",
    summary: "Ron Jon Surf School, después de Kennedy.",
    placeId: "cocoa",
  },
  {
    id: "universal",
    date: "2026-10-05",
    time: "09:00",
    instant: "2026-10-05T09:00:00-04:00",
    clock: "Orlando",
    title: "Universal Studios",
    summary: "Apertura en Diagon Alley: Gringotts primero.",
    placeId: "universal",
    reservationId: "universal",
    plan: [
      "Directo a Harry Potter and the Escape from Gringotts.",
      "Después, Revenge of the Mummy y Men in Black.",
      "Transformers y Minion Mayhem.",
      "De noche, el dragón y los callejones iluminados.",
    ],
  },
  {
    id: "islands",
    date: "2026-10-06",
    time: "09:00",
    instant: "2026-10-06T09:00:00-04:00",
    clock: "Orlando",
    title: "Islands of Adventure",
    summary: "Hagrid apenas abran, y VelociCoaster al lado.",
    placeId: "islands",
    reservationId: "islands",
    plan: [
      "Hagrid’s Magical Creatures Motorbike Adventure.",
      "VelociCoaster.",
      "Agua solo si quieren: River Adventure y los rápidos de Popeye.",
      "Hulk y Spider-Man.",
    ],
  },
  {
    id: "vuelo-vuelta",
    date: "2026-10-10",
    time: "09:10",
    endTime: "19:15",
    instant: "2026-10-10T09:10:00-04:00",
    clock: "Miami",
    title: "Vuelo a Buenos Aires",
    summary: "AR1305 desde Miami. Llega 19:15. Sin bodega incluida.",
    reservationId: "vuelo-vuelta",
    plan: [
      "Salir desde MIA, no desde Orlando.",
      "09:10 despegue.",
      "Llegada 19:15.",
    ],
  },
  {
    id: "surf-nov",
    date: "2026-11-05",
    time: "09:00",
    endTime: "17:00",
    instant: "2026-11-05T09:00:00-05:00",
    clock: "Orlando",
    title: "Cocoa Beach",
    summary: "Figura en la agenda como pendiente. Pedir un mapa.",
    placeId: "cocoa",
    reservationId: "surf",
  },
];

export const tripMapUrl = "https://maps.app.goo.gl/NtBNTgghowsDeJK1A";

export const placeCategories = [
  "Parques",
  "Compras",
  "Playas",
  "Paseos",
  "Alojamiento",
] as const;

export const reservationCategories = [
  { id: "todas", label: "Todas" },
  { id: "vuelo", label: "Vuelos" },
  { id: "hotel", label: "Hotel" },
  { id: "entrada", label: "Entradas" },
  { id: "seguro", label: "Seguro" },
  { id: "actividad", label: "Actividades" },
] as const;

export function placeById(id?: string) {
  return places.find((place) => place.id === id);
}

export function reservationById(id?: string) {
  return reservations.find((reservation) => reservation.id === id);
}

export function itineraryById(id: string) {
  return itinerary.find((item) => item.id === id);
}
